application: scriptaga
version: 1
runtime: go
api_version: go1

handlers:
- url: /app/.*
  script: _go_app

- url: /css/(.*\.css)
  static_files: css/\1
  upload: css/.*\.css

- url: /js/(.*\.js)
  static_files: js/\1
  upload: js/.*\.js

- url: /(.*\.html)
  static_files: html/\1
  upload: html/.*\.html

- url: /
  static_files: html/index.html
  upload: html/index\.html
